# Generated by Django 3.2.4 on 2021-06-11 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_description', models.CharField(max_length=250)),
                ('date_of_payment', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_profile.patientprofile')),
            ],
        ),
    ]
