# Generated by Django 3.2.4 on 2021-08-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laxity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laxity_positive_points', models.CharField(max_length=200)),
                ('mandibular_manipulation', models.CharField(max_length=200)),
                ('premature_contact_point', models.CharField(max_length=200)),
                ('max_opening', models.CharField(max_length=200)),
                ('mandibular_opening_deviation', models.CharField(max_length=200)),
                ('laterality', models.CharField(max_length=200)),
                ('condylar_mobility', models.CharField(max_length=200)),
                ('articulary_noises', models.CharField(max_length=200)),
                ('presuntive_dx_articular', models.CharField(max_length=200)),
                ('diagnose', models.CharField(max_length=200)),
                ('treatment_plan', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_profile.patientprofile')),
            ],
        ),
    ]
