# Generated by Django 3.2.4 on 2021-08-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_side_pain_1', models.PositiveSmallIntegerField(default=0)),
                ('right_side_pain_2', models.PositiveSmallIntegerField(default=0)),
                ('right_side_pain_3', models.PositiveSmallIntegerField(default=0)),
                ('right_side_pain_4', models.PositiveSmallIntegerField(default=0)),
                ('right_side_pain_5', models.PositiveSmallIntegerField(default=0)),
                ('right_side_pain_6', models.PositiveSmallIntegerField(default=0)),
                ('right_side_pain_7', models.PositiveSmallIntegerField(default=0)),
                ('right_side_pain_8', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_1', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_2', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_3', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_4', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_5', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_6', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_7', models.PositiveSmallIntegerField(default=0)),
                ('left_side_pain_8', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_profile.patientprofile')),
            ],
        ),
    ]
