# Generated by Django 3.2.4 on 2021-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_palpation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclepalpation',
            name='digastric_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='digastric_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='ecm_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='ecm_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='masseter_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='masseter_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='occipital_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='occipital_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='pc_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='pc_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='temporalis_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='temporalis_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='trapezius_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musclepalpation',
            name='trapezius_right',
            field=models.BooleanField(default=False),
        ),
    ]
