# Generated by Django 3.2.7 on 2021-10-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_palpation', '0002_auto_20210831_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclepalpation',
            name='note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
