# Generated by Django 3.2.4 on 2021-06-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthodontic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facial_profile', models.CharField(max_length=200)),
                ('molar_class', models.CharField(max_length=200)),
                ('canine_class', models.CharField(max_length=200)),
                ('crossbite', models.CharField(max_length=200)),
                ('habits', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_profile.patientprofile')),
            ],
        ),
    ]
