# Generated by Django 3.2.4 on 2021-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthodontic', '0002_orthodontic_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthodontic',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
