# Generated by Django 3.2.7 on 2021-10-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orthodontic', '0003_alter_orthodontic_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthodontic',
            name='note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
