from django.forms import ModelForm, fields, DateInput
from .models import PatientProfile


class PatientProfileForm(ModelForm):
    class Meta:
        model = PatientProfile
        fields = ['name',
                  'occupation',
                  'phone_number',
                  'address',
                  'birthday',
                  'city_of_birth',
                  'email',
                  'recommended_by',
                  'motive_of_consultancy',
                  'heart_problems',
                  'epilepsy',
                  'high_blood_pressure',
                  'headache',
                  'low_blood_pressure',
                  'hepatitis_or_liver_disease',
                  'circulatory_problems',
                  'cancer',
                  'nervous_problems',
                  'psychiatric_treatment',
                  'radiotherapy',
                  'chronic_diarrhea',
                  'artificial_heart_valves',
                  'anesthesia_allergy',
                  'recent_weight_loss',
                  'medicine_allergy',
                  'diabetes',
                  'general_allergies',
                  'respiratory_disease',
                  'blood_disease',
                  'arthritis',
                  'hiv_aids',
                  'drug_allergy',
                  'which_drug_allergy',
                  'taking_medication',
                  'which_medication',
                  'under_medical_care',
                  'why_under_medical_care',
                  'might_be_pregnant',
                  'any_other_thing',
                  'orthodontics_brackets',
                  'bad_bite',
                  'facial_pain',
                  'face_jaw_hit',
                  'comb_pain',
                  'hard_close_teeth',
                  'eye_ear_face_pain',
                  'neck_stiffness',
                  'teeth_grind_sleep',
                  'wake_teeth_pain',
                  'hand_fingers_numbness',
                  'ear_noise',
                  'dizziness_and_nausea',
                  'temporomandibular_joint_pain',
                  'mandibular_joint_click_noise',
                  'mandibular_joint_treatment',
                  'fibromyalgia_diagnosis',
                  'sleep_disturbance',
                  'wake_up_tired',
                  'aspirin_or_other_analgesic',
                  'nail_tongue_lips_bite',
                  'chew_gum',
                  'perfectionist',
                  'nervous_anxious',
                  'muscle_relaxer_tranquilizers_antidepressants',
                  'open_jaw_lock',
                  'bitting_comfortable',
                  'open_mouth_a_lot',
                  'recent_life_change',
                  'nervous_tension',
                  'headache_pains_questionnaire',
                  'bilateral_unilateral_headache',
                  'pulsating_headache',
                  'migraine'
                  ]
        widgets = {
            'birthday': DateInput(format=('%d-%m-%Y'),
                                  attrs={'label': 'birthday',
                'placeholder': 'dd-mm-yyyy',
                'type': 'date'})
        }


class PatientUpdateProfileForm(ModelForm):
    class Meta:
        model = PatientProfile
        fields = ['name',
                  'image',
                  'occupation',
                  'phone_number',
                  'address',
                  'birthday',
                  'city_of_birth',
                  'email',
                  'recommended_by',
                  'motive_of_consultancy',
                  'heart_problems',
                  'epilepsy',
                  'high_blood_pressure',
                  'headache',
                  'low_blood_pressure',
                  'hepatitis_or_liver_disease',
                  'circulatory_problems',
                  'cancer',
                  'nervous_problems',
                  'psychiatric_treatment',
                  'radiotherapy',
                  'chronic_diarrhea',
                  'artificial_heart_valves',
                  'anesthesia_allergy',
                  'recent_weight_loss',
                  'medicine_allergy',
                  'diabetes',
                  'general_allergies',
                  'respiratory_disease',
                  'blood_disease',
                  'arthritis',
                  'hiv_aids',
                  'drug_allergy',
                  'which_drug_allergy',
                  'taking_medication',
                  'which_medication',
                  'under_medical_care',
                  'why_under_medical_care',
                  'might_be_pregnant',
                  'any_other_thing',
                  'orthodontics_brackets',
                  'bad_bite',
                  'facial_pain',
                  'face_jaw_hit',
                  'comb_pain',
                  'hard_close_teeth',
                  'eye_ear_face_pain',
                  'neck_stiffness',
                  'teeth_grind_sleep',
                  'wake_teeth_pain',
                  'hand_fingers_numbness',
                  'ear_noise',
                  'dizziness_and_nausea',
                  'temporomandibular_joint_pain',
                  'mandibular_joint_click_noise',
                  'mandibular_joint_treatment',
                  'fibromyalgia_diagnosis',
                  'sleep_disturbance',
                  'wake_up_tired',
                  'aspirin_or_other_analgesic',
                  'nail_tongue_lips_bite',
                  'chew_gum',
                  'perfectionist',
                  'nervous_anxious',
                  'muscle_relaxer_tranquilizers_antidepressants',
                  'open_jaw_lock',
                  'bitting_comfortable',
                  'open_mouth_a_lot',
                  'recent_life_change',
                  'nervous_tension',
                  'headache_pains_questionnaire',
                  'bilateral_unilateral_headache',
                  'pulsating_headache',
                  'migraine'
                  ]
        # widgets = {
        #     'birthday': DateInput(format=('%d-%m-%Y'),
        #                           attrs={'label': 'birthday',
        #         'placeholder': 'dd-mm-yyyy',
        #         'type': 'date'})
        # }
